[project]
name = "nodered-dmp"
version = "0.1.0"
description = "Node-RED Data Mapping Processor"
requires-python = ">=3.14"
dependencies = [
    "nodered-flowgen",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
    "tinydb>=4.8.2",
]

[tool.uv.sources]
nodered-flowgen = { path = "../nodered-flowgen", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["."]
